--
-- PostgreSQL database dump
--

\restrict U5LpNSFhuBgU6ZJPJkvt9GnimTdHLLGuiJPUZL7SJ7v3rhXgpg6FlEajoPHpSAQ

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-05-18 23:38:30

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 228 (class 1259 OID 16624)
-- Name: artists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.artists (
    artist_id integer NOT NULL,
    artist_name character varying NOT NULL
);


ALTER TABLE public.artists OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16623)
-- Name: artists_artist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.artists ALTER COLUMN artist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.artists_artist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16663)
-- Name: booking_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.booking_details (
    booking_detail_id integer NOT NULL,
    booking_id integer NOT NULL,
    config_id integer NOT NULL,
    quantity integer NOT NULL,
    event_day_id integer NOT NULL
);


ALTER TABLE public.booking_details OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16662)
-- Name: booking_details_booking_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.booking_details ALTER COLUMN booking_detail_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_details_booking_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16648)
-- Name: bookings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bookings (
    booking_id integer NOT NULL,
    schedule_id integer NOT NULL,
    customer_name character varying NOT NULL,
    phone character varying NOT NULL,
    email character varying NOT NULL,
    payment_account character varying,
    payment_status character varying DEFAULT 'Pending'::character varying,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.bookings OWNER TO postgres;

--
-- TOC entry 5088 (class 0 OID 0)
-- Dependencies: 232
-- Name: COLUMN bookings.payment_account; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.bookings.payment_account IS 'Saved for automatic refund if the event is canceled';


--
-- TOC entry 231 (class 1259 OID 16647)
-- Name: bookings_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bookings ALTER COLUMN booking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16673)
-- Name: e_tickets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.e_tickets (
    ticket_code character varying NOT NULL,
    booking_detail_id integer NOT NULL,
    ticket_status character varying DEFAULT 'Valid'::character varying
);


ALTER TABLE public.e_tickets OWNER TO postgres;

--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 235
-- Name: COLUMN e_tickets.ticket_code; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.e_tickets.ticket_code IS 'QR Code or digital ticket ID sent via SMS/Email';


--
-- TOC entry 5090 (class 0 OID 0)
-- Dependencies: 235
-- Name: COLUMN e_tickets.ticket_status; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.e_tickets.ticket_status IS 'Valid, Used, Canceled';


--
-- TOC entry 226 (class 1259 OID 16614)
-- Name: event_artists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event_artists (
    event_artist_id integer NOT NULL,
    artist_id integer NOT NULL,
    event_day_id integer NOT NULL,
    is_backup boolean DEFAULT false
);


ALTER TABLE public.event_artists OWNER TO postgres;

--
-- TOC entry 5091 (class 0 OID 0)
-- Dependencies: 226
-- Name: COLUMN event_artists.is_backup; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.event_artists.is_backup IS 'Must ensure at least 2 backup artists per event-venue pair';


--
-- TOC entry 225 (class 1259 OID 16613)
-- Name: event_artists_event_artist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.event_artists ALTER COLUMN event_artist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_artists_event_artist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16684)
-- Name: event_days; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event_days (
    event_day_id integer NOT NULL,
    event_schedule_id integer NOT NULL,
    date timestamp without time zone NOT NULL
);


ALTER TABLE public.event_days OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16683)
-- Name: event_days_event_day_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.event_days ALTER COLUMN event_day_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_days_event_day_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16605)
-- Name: event_schedules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event_schedules (
    schedule_id integer NOT NULL,
    event_id integer NOT NULL,
    venue_id integer NOT NULL
);


ALTER TABLE public.event_schedules OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16604)
-- Name: event_schedules_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.event_schedules ALTER COLUMN schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_schedules_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16583)
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    event_id integer NOT NULL,
    event_name character varying NOT NULL,
    description text,
    number_of_days integer
);


ALTER TABLE public.events OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16582)
-- Name: events_event_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16634)
-- Name: ticket_configs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_configs (
    config_id integer NOT NULL,
    schedule_id integer NOT NULL,
    ticket_type character varying NOT NULL,
    price numeric DEFAULT 0 NOT NULL,
    max_quantity integer NOT NULL
);


ALTER TABLE public.ticket_configs OWNER TO postgres;

--
-- TOC entry 5092 (class 0 OID 0)
-- Dependencies: 230
-- Name: COLUMN ticket_configs.ticket_type; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.ticket_configs.ticket_type IS 'e.g., VIP, Standard, Free Invitation';


--
-- TOC entry 5093 (class 0 OID 0)
-- Dependencies: 230
-- Name: COLUMN ticket_configs.max_quantity; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.ticket_configs.max_quantity IS 'Total tickets allocated for this type';


--
-- TOC entry 229 (class 1259 OID 16633)
-- Name: ticket_configs_config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket_configs ALTER COLUMN config_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_configs_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16593)
-- Name: venues; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venues (
    venue_id integer NOT NULL,
    venue_name character varying NOT NULL,
    capacity integer NOT NULL,
    city character varying NOT NULL
);


ALTER TABLE public.venues OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16592)
-- Name: venues_venue_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.venues ALTER COLUMN venue_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venues_venue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4914 (class 2606 OID 16632)
-- Name: artists artists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.artists
    ADD CONSTRAINT artists_pkey PRIMARY KEY (artist_id);


--
-- TOC entry 4920 (class 2606 OID 16672)
-- Name: booking_details booking_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking_details
    ADD CONSTRAINT booking_details_pkey PRIMARY KEY (booking_detail_id);


--
-- TOC entry 4918 (class 2606 OID 16661)
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (booking_id);


--
-- TOC entry 4922 (class 2606 OID 16682)
-- Name: e_tickets e_tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.e_tickets
    ADD CONSTRAINT e_tickets_pkey PRIMARY KEY (ticket_code);


--
-- TOC entry 4912 (class 2606 OID 16622)
-- Name: event_artists event_artists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_artists
    ADD CONSTRAINT event_artists_pkey PRIMARY KEY (event_artist_id);


--
-- TOC entry 4924 (class 2606 OID 16691)
-- Name: event_days event_days_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_days
    ADD CONSTRAINT event_days_pkey PRIMARY KEY (event_day_id);


--
-- TOC entry 4910 (class 2606 OID 16612)
-- Name: event_schedules event_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_schedules
    ADD CONSTRAINT event_schedules_pkey PRIMARY KEY (schedule_id);


--
-- TOC entry 4906 (class 2606 OID 16591)
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (event_id);


--
-- TOC entry 4916 (class 2606 OID 16646)
-- Name: ticket_configs ticket_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_configs
    ADD CONSTRAINT ticket_configs_pkey PRIMARY KEY (config_id);


--
-- TOC entry 4908 (class 2606 OID 16603)
-- Name: venues venues_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venues
    ADD CONSTRAINT venues_pkey PRIMARY KEY (venue_id);


--
-- TOC entry 4931 (class 2606 OID 16722)
-- Name: booking_details booking_details_booking_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking_details
    ADD CONSTRAINT booking_details_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id) DEFERRABLE;


--
-- TOC entry 4932 (class 2606 OID 16727)
-- Name: booking_details booking_details_config_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking_details
    ADD CONSTRAINT booking_details_config_id_fkey FOREIGN KEY (config_id) REFERENCES public.ticket_configs(config_id) DEFERRABLE;


--
-- TOC entry 4933 (class 2606 OID 16742)
-- Name: booking_details booking_details_event_day_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking_details
    ADD CONSTRAINT booking_details_event_day_id_fkey FOREIGN KEY (event_day_id) REFERENCES public.event_days(event_day_id) DEFERRABLE;


--
-- TOC entry 4930 (class 2606 OID 16717)
-- Name: bookings bookings_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.event_schedules(schedule_id) DEFERRABLE;


--
-- TOC entry 4934 (class 2606 OID 16732)
-- Name: e_tickets e_tickets_booking_detail_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.e_tickets
    ADD CONSTRAINT e_tickets_booking_detail_id_fkey FOREIGN KEY (booking_detail_id) REFERENCES public.booking_details(booking_detail_id) DEFERRABLE;


--
-- TOC entry 4927 (class 2606 OID 16702)
-- Name: event_artists event_artists_artist_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_artists
    ADD CONSTRAINT event_artists_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(artist_id) DEFERRABLE;


--
-- TOC entry 4928 (class 2606 OID 16707)
-- Name: event_artists event_artists_event_day_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_artists
    ADD CONSTRAINT event_artists_event_day_id_fkey FOREIGN KEY (event_day_id) REFERENCES public.event_days(event_day_id) DEFERRABLE;


--
-- TOC entry 4935 (class 2606 OID 16737)
-- Name: event_days event_days_event_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_days
    ADD CONSTRAINT event_days_event_schedule_id_fkey FOREIGN KEY (event_schedule_id) REFERENCES public.event_schedules(schedule_id) DEFERRABLE;


--
-- TOC entry 4925 (class 2606 OID 16692)
-- Name: event_schedules event_schedules_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_schedules
    ADD CONSTRAINT event_schedules_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(event_id) DEFERRABLE;


--
-- TOC entry 4926 (class 2606 OID 16697)
-- Name: event_schedules event_schedules_venue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_schedules
    ADD CONSTRAINT event_schedules_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(venue_id) DEFERRABLE;


--
-- TOC entry 4929 (class 2606 OID 16712)
-- Name: ticket_configs ticket_configs_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_configs
    ADD CONSTRAINT ticket_configs_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.event_schedules(schedule_id) DEFERRABLE;


-- Completed on 2026-05-18 23:38:31

--
-- PostgreSQL database dump complete
--

\unrestrict U5LpNSFhuBgU6ZJPJkvt9GnimTdHLLGuiJPUZL7SJ7v3rhXgpg6FlEajoPHpSAQ

